### ISSUE TITLE
خطا DOMException

### ISSUE THREAD

**Issue by bahar-1396** [farshaddavoudi/Blazor.PersianDatePicker#39]
Uncaught DOMException: Element.matches: '[object HTMLInputElement]' is not a valid selector
زمانیکه تاریخ انتخاب میکنیم چنین خطایی صادر میشود لطفا بررسی شود

**Comment by fericode** [comment]
You can use the lib though, the DOMException don't has any functionality effect.

**Comment by farshaddavoudi** [comment]
This issue was closed and has been resolved in version >= 2.1.1. Thanks for all the patience.
