### ISSUE TITLE
ست نکردن تاریخ در فرم ویرایش

### ISSUE THREAD

**Issue by 0098** [farshaddavoudi/Blazor.PersianDatePicker#40]
سلام
در فرم ثبت که کاربر تاریخ رو انتخاب میکنه بدون مشکل کار انجام میشه
ولی در فرم ویرایش که میخواد تاریخ رو ویرایش کنه,  تاریخ روز جاری رو نشون میده

**Comment by fericode** [comment]
سلام و ممنون از ارسال مشکل. شما درست میگید چشم ردیفش می‌کنیم

**Comment by EsmaeelAmarloo** [comment]
Hi .when i set parameter Value to '1402/01/01' and then click on input, selected day in datepicker is today not '1402/01/01'
