### ISSUE TITLE
net::ERR_ABORTED 404 for CSS file

### ISSUE THREAD

**Issue by mhdr** [farshaddavoudi/Blazor.PersianDatePicker#57]
I'm using PersianDatePicker Version 3.0.1 on .NET 7
![Screenshot 2023-01-10 090639](https://user-images.githubusercontent.com/10972572/211470154-44f4d4ba-c839-40fd-96a7-1822e641cd3d.png)

**Comment by farshaddavoudi** [comment]
It should have been fixed by now. Thanks for sharing and sorry for late answer.
