### ISSUE TITLE
choose past dates

### ISSUE THREAD

**Issue by majidmohamadisamani** [farshaddavoudi/Blazor.PersianDatePicker#85]
Hi
Good time
How to choose past dates?

**Comment by farshaddavoudi** [comment]
Hi @majidmohamadisamani 

I'm not sure if I have understood your question precisely. The default setting prevents the user from selecting a date before today (making past dates gray and unselectable in the picker). We can change that by an option provided in the component. Just use `MinDateSetOnToday="false"` on datepicker declaration (default is _true_).

**Comment by majidmohamadisamani** [comment]
Hi @farshaddavoudi
Yes, exactly

**Comment by majidmohamadisamani** [comment]
Hi @farshaddavoudi
Yes, exactly

Thanks
