### ISSUE TITLE
مشکل در نمایش سال کبیسه

### ISSUE THREAD

**Issue by web724online** [farshaddavoudi/Blazor.PersianDatePicker#89]
من داخل پروژه ام از این تقویم استفاده کرده ام ولی در نمایش تقویم سال 1403 که سال کبیسه است مشکل دارد و اسفند را 29 روز نشان میدهد و سال 1404 را کبیسه محاسبه کرده است.
این مشکل وقتی بدتر میشه که این مورد باعث میشه تاریخ ها در کل سال 1404 یک روز جابجا بشوند.
این مشکل فقط بخش نمایش تقویمه و خود کامپوننت تاریخ درست رو نمایش میده. و بخاطر مینیفای بودن جاوااسکریپتش اصلاح کردنش سخته. ی بخشهایی رو اصلاح کردم ولی آخرش درست نشد.

**Comment by farshaddavoudi** [comment]
سلام ممنون از پیامتون. این موضوع رو دیدم و حتما روش کار می‌کنم. تا هفته دیگه اصلاحش می‌کنم و نسخه جدید رو میزارم

**Comment by farshaddavoudi** [comment]
Fixed

**Comment by seyedjamalfazeli** [comment]
سلام وقت بخیر
اول از زحمت تون بابت تقویم شمسی ممنونم
جسارتا مشکل سال کبیسه ۱۴۰۳ به درستی در نسخه های ۳.۴ به بعد هنوز کار نمی کند و برای سال بعد را به عنوان سال کبیسه در نظر میگیره که اشتباه هست
ممنون میشم این مورد رو اصلاح کنید(چون در حال حاضر داره استفاده میشه و به مشکل خوردیم)

**Comment by seyedjamalfazeli** [comment]
منظورم فقط در نمایش متن انتخاب شده هست که اشتباه است

![Image](https://github.com/user-attachments/assets/12c27336-edd2-471e-879d-da4fd5be7499)

**Comment by farshaddavoudi** [comment]
لطفا پکیج را به آخرین ورژن آپدیت کنید

**Comment by seyedjamalfazeli** [comment]
این نسخه ای که براش مشکل پیش اومده در نسخه ۳.۵.۱ هست که آپدیت کردم توی پروژه خودم ولی هنوز مشکل داره
حالا اگر نیاز هست و امکانش هست که شماره موبایل خودم  رو بذارم برای ارتباط مستقیم و انتقال مفهوم؟

**Comment by farshaddavoudi** [comment]
شما یه زحمتی بکشید. یه نیو پروجکت بزنید و بعد پکیج نصب و استفاده کنید و ببینید اگه همین مشکل داره بهم اطلاع بدید

**Comment by seyedjamalfazeli** [comment]
جناب این درست کار می‌کنه
من باید فایل js رو هم بروز میکردم
ممنون بابت وقتی که گذاشتین

**Comment by farshaddavoudi** [comment]
خواهش می‌کنم. خوشحالم مشکلتون حل شده. 
موفق باشید

**Comment by alirezaseif28** [comment]
> جناب این درست کار می‌کنه من باید فایل js رو هم بروز میکردم ممنون بابت وقتی که گذاشتین

سلام میشه فایل
 js
بفرستید

**Comment by farshaddavoudi** [comment]
@alirezaseif28 فایل خاصی نیست. مطابق راهنمای ریدمی برید کار می‌کنه
فایلی هم خواستید توی خود ریپو هست می‌تونید پیدا کنید.
موفق باشید
