### ISSUE TITLE
Show holidays

### ISSUE THREAD

**Issue by Mostafa-Moradi** [farshaddavoudi/Blazor.PersianDatePicker#93]
Please specify the holidays with their corresponding colors. Additionally, if possible, allow users to manually register a specific day with a specific color in the component.

**Comment by farshaddavoudi** [comment]
@Mostafa-Moradi The feature has been successfully implemented.

**Comment by Mostafa-Moradi** [comment]
@farshaddavoudi 
Dear Farshad, 
Thank you very much

**Comment by farshaddavoudi** [comment]
YW @Mostafa-Moradi. If you want to add/modify the holidays, you can update the `Holidays.cs` class and create a PR. Particularly I'm not sure wether to include Fridays in the holidays or not.
